version = 0.1
[default.deploy.parameters]
stack_name = "stable-diffusion-on-ec2"
resolve_s3 = true
s3_prefix = "stable-diffusion-on-ec2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "InstanceType=\"g5g.xlarge\""
image_repositories = []
